export const SET_CHANNELS = 'SET_CHANNELS';
export const SET_CHANNEL_POSTS = 'SET_CHANNEL_POSTS';

export const SET_PLANTS = 'SET_PLANTS';

export const SET_USER = 'SET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const ADD_GARDEM_PLANT = 'ADD_GARDEM_PLANT';
export const REMOVE_GARDEM_PLANT = 'REMOVE_GARDEM_PLANT';
export const ADD_FOLLOWED_CHANNEL = 'ADD_FOLLOWED_CHANNEL';
export const REMOVE_FOLLOWED_CHANNEL = 'REMOVE_FOLLOWED_CHANNEL';